### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nsisodiya** [nsisodiya/tinyview#1]
- [ ] todo SEO friendly (render from server)
- [ ]  more plugins
- [x]  webpack and other
- [x]  demo
- [ ]  routing example
- [ ]  write article on this framework
